# .github/workflows/ci-pipeline.yml

name: Python CI Pipeline

# This workflow runs on any push or pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # The workflow will run on a virtual machine running the latest Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository's code so the job can access it
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Sets up the Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. Installs your project dependencies from pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          python -m textblob.download_corpora # Pre-download NLTK data for tests

      # 4. Runs the tests using pytest
      - name: Run tests
        run: |
          pytest